name: rwg_home_core
description: A Dart client used by the RWG home application.
version: 1.0.0
repository: https://github.com/Venatrixx/rwg_home_core

publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  home_info_point_client:
    git:
      url: https://github.com/Venatrixx/home_info_point_client
      ref: v1.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  xml: ^6.5.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
